import { QuizQuestion } from "./questionsInterfaces";

export enum QuestionsAndCorrectAnswers{
    LongRiver = '¿Cuál es el río más largo del mundo?',
    LongRiverAnswer = 'Amazonas',
    CristobalColon = '¿En qué año llegó Cristóbal Colón a América?',
    CristobalColonAnswer = '1492',
    BiggestOcean = '¿Cuál es el océano más grande del mundo?',
    BiggestOceanAnswer = 'Océano Pacífico',
    SumNumbers = '¿Cúal es resultado de 3 + 4',
    SumNumbersAnswer = '7',
    Heptagon = '¿Cuántos lados tiene un heptágono?',
    HeptagonAnswer = '7',
    BiggestAnimal = '¿Cuál es el animal más grande de la Tierra?',
    BiggestAnimalAnswer = 'La ballena azul',
    HardestMineral = '¿Cuál es el mineral más duro del planeta?',
    HardestMineralAnswer = 'Diamante',
    HumanSpace = '¿En qué año el ser humano llegó al espacio?',
    HumanSpaceAnswer = '1961',
    AtomParticles = '¿Qué partícula pertenece a un átomo?',
    AtomParticlesAnswer = 'Protones',
    PrimaryColors = '¿Cuál es un color primario?',
    PrimaryColorsAnswer = 'Azul',
}

export enum QuestionsincorrectAnwers{
    LongRiverIncorrectOne = 'Guadalquivir',
    LongRiverIncorrectTwo = 'Nilo',
    BiggestOceanIncorrectOne = 'Atlántico',
    BiggestOceanIncorrectTwo = 'Ártico',
    BiggestAnimalIncorrectOne = 'León',
    BiggestAnimalIncorrectTwo = 'Elefante',
    HumanSpaceIncorrectOne = '1890',
    HumanSpaceIncorrectTwo = '1995',
    AtomParticlesIncorrectOne = 'Neutrino',
    AtomParticlesIncorrectTwo = 'Molécula',
    PrimaryColorsIncorrectOne = 'Naranja',
    PrimaryColorsIncorrectTwo = 'Verde',
}

export const quizQuestions: QuizQuestion[] = [
    {
        question: QuestionsAndCorrectAnswers.LongRiver,
        answers: [
            {answer: QuestionsAndCorrectAnswers.LongRiverAnswer, correct: true, id: 1},
            {answer: QuestionsincorrectAnwers.LongRiverIncorrectOne, correct: false, id: 2},
            {answer: QuestionsincorrectAnwers.LongRiverIncorrectTwo, correct: false, id: 3},
        ],
        id: 1,
        type:'select',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.CristobalColon,
        answers: [{answer: QuestionsAndCorrectAnswers.CristobalColonAnswer, correct: true, id: 1}],
        id: 2,
        type:'input',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.BiggestOcean,
        answers: [
            {answer: QuestionsincorrectAnwers.BiggestOceanIncorrectOne, correct: false, id: 1},
            {answer: QuestionsincorrectAnwers.BiggestOceanIncorrectTwo, correct: false, id: 2},
            {answer: QuestionsAndCorrectAnswers.BiggestOceanAnswer, correct: true, id: 3},
        ],
        id: 3,
        type:'select',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.SumNumbers,
        answers: [{answer: QuestionsAndCorrectAnswers.SumNumbersAnswer, correct: true, id: 1}],
        id: 4,
        type:'input',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.Heptagon,
        answers: [{answer: QuestionsAndCorrectAnswers.HeptagonAnswer, correct: true, id: 1}],
        id: 5,
        type:'input',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.BiggestAnimal,
        answers: [
            {answer: QuestionsincorrectAnwers.BiggestAnimalIncorrectOne, correct: false, id: 1},
            {answer: QuestionsAndCorrectAnswers.BiggestAnimalAnswer, correct: true, id: 2},
            {answer: QuestionsincorrectAnwers.BiggestAnimalIncorrectTwo, correct: false, id: 3},
        ],
        id: 6,
        type:'select',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.HardestMineral,
        answers: [{answer: QuestionsAndCorrectAnswers.HardestMineralAnswer, correct: true, id: 1}],
        id: 7,
        type:'input',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.HumanSpace,
        answers: [
            {answer: QuestionsAndCorrectAnswers.HumanSpaceAnswer, correct: true, id: 1},
            {answer: QuestionsincorrectAnwers.HumanSpaceIncorrectOne, correct: false, id: 2},
            {answer: QuestionsincorrectAnwers.HumanSpaceIncorrectTwo, correct: false, id: 3},
        ],
        id: 8,
        type:'select',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.AtomParticles,
        answers: [
            {answer: QuestionsAndCorrectAnswers.AtomParticlesAnswer, correct: true, id: 1},
            {answer: QuestionsincorrectAnwers.AtomParticlesIncorrectOne, correct: false, id: 2},
            {answer: QuestionsincorrectAnwers.AtomParticlesIncorrectTwo, correct: false, id: 3},
        ],
        id: 9,
        type:'select',
        success: false,
        userAnswer: '',
    },
    {
        question: QuestionsAndCorrectAnswers.PrimaryColors,
        answers: [
            {answer: QuestionsincorrectAnwers.PrimaryColorsIncorrectOne, correct: false, id: 1},
            {answer: QuestionsincorrectAnwers.PrimaryColorsIncorrectTwo, correct: false, id: 2},
            {answer: QuestionsAndCorrectAnswers.PrimaryColorsAnswer, correct: true, id: 3},
        ],
        id: 10,
        type:'select',
        success: false,
        userAnswer: '',
    },

]
